# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "disciplines", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "events", :force => true do |t|
    t.column "name",        :string
    t.column "held_on",     :datetime
    t.column "address",     :string
    t.column "city",        :string
    t.column "state",       :string
    t.column "zip",         :string
    t.column "location",    :string
    t.column "description", :text
    t.column "type_id",     :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "speakers",    :text
  end

  create_table "events_users", :id => false, :force => true do |t|
    t.column "user_id",  :integer
    t.column "event_id", :integer
  end

  create_table "news_items", :force => true do |t|
    t.column "name",       :string
    t.column "body",       :text
    t.column "created_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "pages", :force => true do |t|
    t.column "name",       :string
    t.column "body",       :text
    t.column "created_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "resources", :force => true do |t|
    t.column "user_id",     :integer
    t.column "event_id",    :integer
    t.column "name",        :string
    t.column "local_uri",   :string
    t.column "remote_uri",  :text
    t.column "description", :text
    t.column "view_count",  :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "business_name",             :string
    t.column "business_address",          :string
    t.column "business_city",             :string
    t.column "business_state",            :string
    t.column "business_zip",              :string
    t.column "personal_address",          :string
    t.column "personal_city",             :string
    t.column "personal_state",            :string
    t.column "personal_zip",              :string
    t.column "member_type_id",            :integer
    t.column "phone",                     :string
    t.column "phone_secondary",           :string
    t.column "email_secondary",           :string
    t.column "role_id",                   :integer
    t.column "prefered_contact_method",   :string
    t.column "show_personal_info",        :boolean
    t.column "website",                   :string
    t.column "im",                        :string
    t.column "im_secondary",              :string
    t.column "business_fax",              :string
    t.column "personal_fax",              :string
    t.column "send_emails",               :boolean
    t.column "can_manage_content",        :boolean
    t.column "member_since",              :datetime
    t.column "can_manage_users",          :boolean,                :default => false
    t.column "is_active",                 :boolean,                :default => true
    t.column "discipline_id",             :integer
    t.column "job_title",                 :string
    t.column "business_address2",         :string
  end

end
